diff --git a/Makefile b/Makefile
index 8098282..189e25a 100644
--- a/Makefile
+++ b/Makefile
@@ -399,7 +399,7 @@ KBUILD_CFLAGS   := -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs \
 		   -fno-strict-aliasing -fno-common \
 		   -Werror-implicit-function-declaration \
 		   -Wno-format-security \
-		   -Werror	\
+		   -Wno-error	\
 		   -std=gnu89 $(call cc-option,-fno-PIE)
 
 
